const $=id=>document.getElementById(id);
const STATUS_OPTIONS=["Pending","Design","Production","Ready","Completed","Cancelled"];
let allOrders=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function money(v){return "RM "+Number(v||0).toFixed(2)}
function token(){return $("token").value.trim()}
function message(text,error=false){const el=$("message");el.textContent=text;el.className="message"+(error?" err":"");el.classList.remove("hide")}
function clearMessage(){$("message").classList.add("hide")}
function saveToken(){if(token())sessionStorage.setItem("huffaz_admin_token",token())}
function restoreToken(){const t=sessionStorage.getItem("huffaz_admin_token")||"";if(t)$("token").value=t}
function clearSession(){sessionStorage.removeItem("huffaz_admin_token");$("token").value="";allOrders=[];render([]);message("Admin session locked.")}
function statusOptions(current){return STATUS_OPTIONS.map(s=>`<option value="${esc(s)}" ${s===current?"selected":""}>${esc(s)}</option>`).join("")}
function whatsappUrl(v){const x=String(v||"").replace(/\D/g,"");return x?`https://wa.me/${x}`:"#"}
function summarize(list){const counts={Pending:0,Design:0,Production:0,Ready:0,Completed:0,Cancelled:0};list.forEach(o=>{if(counts[o.status]!==undefined)counts[o.status]++});$("sTotal").textContent=list.length;for(const s of Object.keys(counts)){const el=$("s"+s);if(el)el.textContent=counts[s]}}
function filtered(){const q=$("search").value.trim().toLowerCase();const st=$("status").value;return allOrders.filter(o=>{const hay=[o.reference,o.customer_name,o.whatsapp].join(" ").toLowerCase();return (!q||hay.includes(q))&&(!st||o.status===st)})}
function render(list){summarize(allOrders);if(!list.length){$("orders").innerHTML='<div class="empty">No orders found.</div>';return}$("orders").innerHTML=list.map(o=>{const items=Array.isArray(o.items)?o.items:[];const qty=items.reduce((n,x)=>n+Number(x.quantity||0),0);const detail=items.map(x=>`${esc(x.design_name||x.design||"Ready Design")} • ${esc(x.size||"Size pending")} • ${esc(x.quantity||0)} pcs`).join("<br>");return `<article class="order"><div class="order-head"><div><div class="ref">${esc(o.reference)}</div><div class="date">${esc(o.created_at||"")}</div></div><select class="status" onchange="updateOrder('${esc(o.id)}',{status:this.value})">${statusOptions(o.status)}</select></div><div class="grid"><div class="kv"><small>Customer</small><b>${esc(o.customer_name)}</b></div><div class="kv"><small>WhatsApp</small><b>${esc(o.whatsapp||"")}</b></div><div class="kv"><small>Quantity</small><b>${qty||"—"} pcs</b></div><div class="kv"><small>Total</small><b>${money(o.total)}</b></div></div><details class="detail"><summary>View order details</summary><div class="detail-grid"><div class="kv"><small>Email</small><b>${esc(o.email||"—")}</b></div><div class="kv"><small>Delivery</small><b>${esc(o.location||"—")}</b></div><div class="kv"><small>Deposit</small><b>${money(o.deposit_amount)}</b></div><div class="kv"><small>Paid</small><b>${money(o.paid_amount)}</b></div><div class="kv"><small>Balance</small><b>${money(o.balance)}</b></div><div class="kv"><small>Address</small><b>${esc(o.address||"—")}</b></div></div><p>${detail||"No item details."}</p><p><b>Customer note:</b> ${esc(o.customer_note||"—")}</p></details><div class="actions"><a class="btn wa" href="${whatsappUrl(o.whatsapp)}" target="_blank" rel="noopener">WhatsApp Customer</a><input class="input" id="paid-${esc(o.id)}" type="number" min="0" step="0.01" value="${Number(o.paid_amount||0).toFixed(2)}" placeholder="Paid amount"><button class="btn" type="button" onclick="savePayment('${esc(o.id)}')">Save Payment</button></div><div class="note"><textarea id="note-${esc(o.id)}" rows="2" placeholder="Admin note">${esc(o.admin_note||"")}</textarea><div class="actions"><button class="btn" type="button" onclick="saveNote('${esc(o.id)}')">Save Note</button></div></div></article>`}).join("")}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{"Accept":"application/json",...(options.headers||{}),"x-admin-token":token()}});const txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{throw new Error(txt||`HTTP ${r.status}`)}if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function loadOrders(){if(!token()){message("Please enter ADMIN_TOKEN first.",true);return}saveToken();const btn=$("refresh");btn.disabled=true;btn.textContent="Loading...";try{const p=new URLSearchParams();if($("status").value)p.set("status",$("status").value);if($("search").value.trim())p.set("search",$("search").value.trim());const d=await api("/api/orders"+(p.toString()?"?"+p:""));allOrders=Array.isArray(d.orders)?d.orders:[];render(filtered());message(`${allOrders.length} order(s) loaded.`)}catch(e){message("Error: "+e.message,true);render([])}finally{btn.disabled=false;btn.textContent="Refresh Orders"}}
async function updateOrder(id,patch){try{await api("/api/orders/"+encodeURIComponent(id),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});message("Order updated.");await loadOrders()}catch(e){message("Update failed: "+e.message,true)}}
async function saveNote(id){const el=$("note-"+id);await updateOrder(id,{admin_note:el?el.value:""})}
async function savePayment(id){const el=$("paid-"+id);const value=Math.max(0,Number(el?.value)||0);const order=allOrders.find(x=>x.id===id);await updateOrder(id,{paid_amount:value,total:Number(order?.total||0)})}
$("search").addEventListener("input",()=>render(filtered()));$("status").addEventListener("change",()=>render(filtered()));$("token").addEventListener("keydown",e=>{if(e.key==="Enter")loadOrders()});
restoreToken();window.loadOrders=loadOrders;window.updateOrder=updateOrder;window.saveNote=saveNote;window.savePayment=savePayment;window.clearSession=clearSession;
